stage1:
  base_lr: 0.0001
  disc_lr: 0.0005
  perceptual_weight: 0.001
  adv_weight: 0.01
  kl_weight: 1e-6
  params:
    spatial_dims: 3
    in_channels: 1
    out_channels: 1
    num_channels: [16,32,32]
    latent_channels: 3 
    num_res_blocks: 2
    norm_num_groups: 16
    attention_levels: [False,False,False]
    with_encoder_nonlocal_attn: False
    with_decoder_nonlocal_attn: False
    

discriminator:
  params:
    spatial_dims: 3
    num_channels: 32
    num_layers_d: 3
    in_channels: 1
    out_channels: 1
    padding: 1

perceptual_network:
  params:
    spatial_dims: 3
    network_type: "squeeze"
    fake_3d_ratio: 0.25
