ldm:
  base_lr: 0.00005 
  params:
    spatial_dims: 3
    in_channels: 7
    out_channels: 3
    num_res_blocks: 1 
    num_channels: [64, 64, 64]
    attention_levels: [False, False, True]
    num_head_channels: 64
    transformer_num_layers: 0
    upcast_attention: False 
    with_conditioning: False

  scheduler:
    schedule: "linear_beta"
    num_train_timesteps: 1000
    beta_start: 0.0015
    beta_end: 0.0195
    prediction_type: "v_prediction"
